(define cadr
  (lambda (e) (car (cdr e))))
(cadr (quote ((a b) (c d) e)))
(define (cadr x)
  (car (cdr x)))
(cadr (quote ((a b) (1 2) e)))
(define (add1 x)
  (define a 1)
  (+ x a))
(add1 4)
(define (list. . lst)
  (cond 
    ((eq lst '()) '())
    (else (cons (car lst) 
                (cdr lst)))))
(list. 1 2 '(1 4))